export const USER_ROLE = {
  COMERCIAL_Y_SERVICIOS: 'COMERCIAL_Y_SERVICIOS',
  ORGANICOS: 'ORGANICOS',
  INSTITUCIONES_EDUCATIVAS: 'INSTITUCIONES_EDUCATIVAS',
  EVENTOS_MASIVOS: 'EVENTOS_MASIVOS',
  ENTIDADES_PUBLICAS: 'ENTIDADES_PUBLICAS',
  DESARROLLOS_MULTIFAMILIARES: 'DESARROLLOS_MULTIFAMILIARES',
};
